name: CI
on: [push, pull_request]
jobs:
  jest:
    name: Jest Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.16.1", "20.3.1"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: "8.6.1"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run test

  check:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.16.1", "20.3.1"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: "8.6.1"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run check
